import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const applicationRoot = fileURLToPath(new URL("../", import.meta.url));
const manifestPath = join(applicationRoot, ".fadeno/routes/manifest.json");
const generatedApplicationPath = join(applicationRoot, ".fadeno/routes/app.ts");
const outputPath = join(applicationRoot, ".fadeno/demo-source/application.ts");
const browserModule = "/_fadeno/browser-entry.js";

interface Manifest {
  readonly generation: Readonly<{ sourceSha256: string }>;
  readonly routes: readonly Readonly<{
    kind: "page" | "handler";
    notFound?: string;
  }>[];
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
const generatedApplication = readFileSync(generatedApplicationPath, "utf8");
if (!generatedApplication.startsWith(
  `// Generated by Fadeno application v1; source ${manifest.generation.sourceSha256}.\n`,
)) {
  throw new Error("FADENO_DEMO_ROUTER_GENERATION");
}

const insertion = "generation: applicationGeneration, parameters:";
const pageRoutes = manifest.routes.filter(({ kind }) => kind === "page").length;
const fallbackRoutes = new Set(manifest.routes.flatMap(({ notFound }) => notFound ? [notFound] : [])).size;
const renderCount = generatedApplication.split(insertion).length - 1;
if (renderCount !== pageRoutes + fallbackRoutes) throw new Error("FADENO_DEMO_ROUTER_RENDER_COUNT");

const application = generatedApplication
  .replace(
    `export const applicationGeneration = "${manifest.generation.sourceSha256}";`,
    `export const applicationGeneration = "${manifest.generation.sourceSha256}";\nconst browserModule = ${JSON.stringify(browserModule)};`,
  )
  .replaceAll(insertion, "generation: applicationGeneration, browserModule, parameters:")
  .concat('\nexport { listenNodeHttp } from "@fadeno/framework/node";\n');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, application);
console.log(`Fadeno evaluator router derived from canonical generation ${manifest.generation.sourceSha256}`);
