import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

export interface ApiReferenceEntryPoint {
  readonly importPath: string;
  readonly declarationPath: string;
}

function exportedNames(declaration: string): readonly string[] {
  const names = new Set<string>();
  const pattern = /^export\s+(?:declare\s+)?(?:function|interface|type|class|enum|namespace|const|let|var)\s+([A-Za-z_$][\w$]*)/gmu;
  for (const match of declaration.matchAll(pattern)) {
    names.add(match[1]);
  }
  return [...names].sort((left, right) => left.localeCompare(right));
}

function normalized(path: string): string {
  return readFileSync(path, "utf8").replaceAll("\r\n", "\n").trimEnd();
}

export function renderV1ApiReference(entryPoints: readonly ApiReferenceEntryPoint[]): string {
  const sections = entryPoints.map(({ importPath, declarationPath }) => {
    const declaration = normalized(declarationPath);
    const names = exportedNames(declaration);
    const digest = createHash("sha256").update(declaration).digest("hex");
    return [
      `## \`${importPath}\``,
      "",
      `Exports: ${names.map((name) => `\`${name}\``).join(", ")}.`,
      "",
      `Declaration SHA-256: \`${digest}\`.`,
      "",
      "```ts",
      declaration,
      "```",
    ].join("\n");
  });

  return [
    "# V1 public API reference",
    "",
    "<!-- Generated by scripts/generate-v1-api-reference.ts. Do not edit by hand. -->",
    "",
    "This reference is generated from the declarations emitted by the current",
    "private packed framework. It documents the exact V1 import surfaces without",
    "making the package name, version, or publication status public or stable.",
    "",
    ...sections,
    "",
  ].join("\n");
}
