import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { API } from "typescript/unstable/sync";

import {
  assertContainedOutput,
  classifyModule,
  classifyReachableModule,
  emitAcceptedHandler,
  ExtractionCandidate,
} from "../experiments/extraction/candidate.ts";
import type { ExtractionFixtureId } from "../experiments/extraction/candidate.ts";
import { stableExtractionDiagnosticSnapshots } from "../experiments/extraction/diagnostic-snapshots.ts";
import {
  EXTRACTION_ACCEPTED_CLASSES,
  EXTRACTION_REJECTION_CLASSES,
} from "../experiments/extraction/fixtures/catalog.ts";
import {
  EXTRACTION_DIAGNOSTIC_EXPECTATIONS,
  EXTRACTION_ROOT_EXPORTS,
} from "../experiments/extraction/qualification-contract.ts";
import { scanImports } from "../experiments/extraction/import-scan.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const golden = readFileSync(
  join(root, "experiments/extraction/diagnostics.golden.json"),
  "utf8",
);
if (stableExtractionDiagnosticSnapshots() !== golden) {
  throw new Error("K0-06 extraction diagnostics differ from their golden snapshots");
}

const temporary = mkdtempSync(join(tmpdir(), "fadeno-extraction-candidate-"));
try {
  using candidate = new ExtractionCandidate();
  for (const fixtureId of EXTRACTION_ACCEPTED_CLASSES) {
    const analysis = candidate.analyze(fixtureId);
    if (
      analysis.diagnostic ||
      analysis.rootExport !== EXTRACTION_ROOT_EXPORTS[fixtureId] ||
      !analysis.closureSource.includes("=>") ||
      !analysis.behaviorPath.startsWith("accepted/")
    ) {
      throw new Error(`K0-06 accepted analysis differs: ${fixtureId}`);
    }
  }
  for (const fixtureId of EXTRACTION_REJECTION_CLASSES) {
    const analysis = candidate.analyze(fixtureId);
    const expected = EXTRACTION_DIAGNOSTIC_EXPECTATIONS[fixtureId];
    if (
      !analysis.diagnostic ||
      analysis.diagnostic.id !== expected.id ||
      analysis.diagnostic.severity !== expected.severity ||
      analysis.diagnostic.message !== expected.message ||
      analysis.diagnostic.explanation !== expected.explanation ||
      analysis.diagnostic.correction !== expected.correction ||
      analysis.diagnostic.source !== `rejected/${fixtureId}.ts` ||
      analysis.diagnostic.range.line < 1 ||
      analysis.diagnostic.range.column < 1 ||
      analysis.diagnostic.range.length < 1
    ) {
      throw new Error(`K0-06 rejected analysis differs: ${fixtureId}`);
    }
    const rejectedOutput = join(temporary, "rejected", fixtureId);
    try {
      emitAcceptedHandler(analysis, rejectedOutput);
      throw new Error(`K0-06 rejected emission started: ${fixtureId}`);
    } catch (error: unknown) {
      if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
    }
  }

  const firstRoot = join(temporary, "first");
  const secondRoot = join(temporary, "second");
  for (const fixtureId of EXTRACTION_ACCEPTED_CLASSES) {
    emitAcceptedHandler(candidate.analyze(fixtureId), firstRoot);
    emitAcceptedHandler(candidate.analyze(fixtureId), secondRoot);
  }
  const firstFiles = readdirSync(firstRoot).sort();
  const secondFiles = readdirSync(secondRoot).sort();
  if (JSON.stringify(firstFiles) !== JSON.stringify(secondFiles)) {
    throw new Error("K0-06 generated file inventories differ");
  }
  for (const file of firstFiles) {
    const first = readFileSync(join(firstRoot, file));
    const second = readFileSync(join(secondRoot, file));
    if (!first.equals(second)) throw new Error(`K0-06 generated bytes differ: ${file}`);
    const source = first.toString("utf8");
    if (
      scanImports(source).length !== 0 ||
      /(?:fragment|hydrate|component-runtime|server-only)/u.test(source)
    ) {
      throw new Error(`K0-06 generated handler graph differs: ${file}`);
    }
  }

  const containmentRoot = join(temporary, "contained");
  mkdirSync(containmentRoot);
  for (const destination of [
    join(containmentRoot, "../escape.js"),
    join(containmentRoot, "..", "outside", "escape.js"),
  ]) {
    try {
      assertContainedOutput(containmentRoot, destination);
      throw new Error("K0-06 traversal output was accepted");
    } catch (error: unknown) {
      if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
    }
  }
  const outside = join(temporary, "outside");
  mkdirSync(outside, { recursive: true });
  symlinkSync(outside, join(containmentRoot, "linked"), "dir");
  try {
    assertContainedOutput(containmentRoot, join(containmentRoot, "linked/escape.js"));
    throw new Error("K0-06 symlink output was accepted");
  } catch (error: unknown) {
    if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
  }
} finally {
  rmSync(temporary, { recursive: true, force: true });
}

const metamorphic = mkdtempSync(join(tmpdir(), "fadeno-extraction-metamorphic-"));
try {
  writeFileSync(join(metamorphic, "tsconfig.json"), `${JSON.stringify({
    compilerOptions: { strict: true, target: "ES2022", module: "ES2022" },
    include: ["*.ts"],
  })}\n`);
  writeFileSync(join(metamorphic, "server-only.d.ts"), [
    'declare module "server-only:secrets" { export const secret: string; }',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "renamed-barrel.ts"), [
    'export { secret as renamed } from "server-only:secrets";',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "renamed-handler.ts"), [
    'import { renamed as arbitraryValue } from "./renamed-barrel.ts";',
    "export function arbitraryName(arbitraryParameter: HTMLElement): void {",
    "  arbitraryParameter.textContent = arbitraryValue;",
    "}",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "opaque-one.ts"), [
    "const firstRenamedValue = new AbortController();",
    "export function first(): void { firstRenamedValue.abort(); }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "opaque-two.ts"), [
    "",
    "",
    "const secondRenamedValue = new AbortController();",
    "export function second(renamedParameter: string): void {",
    "  if (renamedParameter) secondRenamedValue.abort();",
    "}",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "call-result.ts"), [
    "function createCapability(): object { return {}; }",
    "const renamedCallResult = createCapability();",
    "export function use(): void { void renamedCallResult; }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "unresolved.ts"), [
    'import { missing } from "./absent.ts";',
    "export function use(): void { void missing; }",
    "",
  ].join("\n"));
  const api = new API({ cwd: metamorphic });
  try {
    const projectPath = join(metamorphic, "tsconfig.json");
    const project = api.updateSnapshot({
      openProjects: [{ uri: new URL(`file://${projectPath}`).href }],
    }).getProjects()[0];
    if (!project) throw new Error("K0-06 metamorphic TypeScript project is absent");
    const source = (name: string) => {
      const file = project.program.getSourceFile({ uri: new URL(`file://${join(metamorphic, name)}`).href });
      if (!file) throw new Error(`K0-06 metamorphic source is absent: ${name}`);
      return file;
    };
    const indirect = classifyReachableModule(project, source("renamed-handler.ts"));
    if (indirect?.id !== "FADENO_K0_EXTRACT_SERVER_IMPORT") {
      throw new Error("K0-06 indirect server flow was accepted");
    }
    const first = classifyModule(source("opaque-one.ts"));
    const second = classifyModule(source("opaque-two.ts"));
    if (
      first?.id !== "FADENO_K0_EXTRACT_OPAQUE_CAPTURE" ||
      second?.id !== first.id ||
      second.range.line === first.range.line
    ) {
      throw new Error("K0-06 renamed/source-shifted opaque flow differs");
    }
    if (
      classifyModule(source("call-result.ts"))?.id !== "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW" ||
      classifyReachableModule(project, source("unresolved.ts"))?.id !==
        "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW"
    ) {
      throw new Error("K0-06 ambiguous flow was accepted");
    }
  } finally {
    api.close();
  }
} finally {
  rmSync(metamorphic, { recursive: true, force: true });
}

console.log(
  `extraction candidate contract passed (${EXTRACTION_ACCEPTED_CLASSES.length} accepted, ${EXTRACTION_REJECTION_CLASSES.length} rejected, ${Object.keys(EXTRACTION_ROOT_EXPORTS).length} roots)`,
);
