import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { API } from "typescript/unstable/sync";
import * as ast from "typescript/unstable/ast";

import {
  assertContainedOutput,
  classifyModule,
  classifyReachableModule,
  classifySelectedClosure,
  emitAcceptedHandler,
  ExtractionCandidate,
  measureCaptureEnvelope,
  measurePlainCapture,
} from "../experiments/extraction/candidate.ts";
import type { ExtractionFixtureId } from "../experiments/extraction/candidate.ts";
import { stableExtractionDiagnosticSnapshots } from "../experiments/extraction/diagnostic-snapshots.ts";
import {
  EXTRACTION_ACCEPTED_CLASSES,
  EXTRACTION_REJECTION_CLASSES,
} from "../experiments/extraction/fixtures/catalog.ts";
import {
  EXTRACTION_DIAGNOSTIC_EXPECTATIONS,
  EXTRACTION_ROOT_EXPORTS,
} from "../experiments/extraction/qualification-contract.ts";
import { scanImports } from "../experiments/extraction/import-scan.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const golden = readFileSync(
  join(root, "experiments/extraction/diagnostics.golden.json"),
  "utf8",
);
if (stableExtractionDiagnosticSnapshots() !== golden) {
  throw new Error("K0-06 extraction diagnostics differ from their golden snapshots");
}

const temporary = mkdtempSync(join(realpathSync(tmpdir()), "fadeno-extraction-candidate-"));
try {
  const candidate = new ExtractionCandidate();
  try {
  for (const fixtureId of EXTRACTION_ACCEPTED_CLASSES) {
    const analysis = candidate.analyze(fixtureId);
    if (
      analysis.diagnostic ||
      analysis.rootExport !== EXTRACTION_ROOT_EXPORTS[fixtureId] ||
      !analysis.closureSource.includes("=>") ||
      !analysis.behaviorPath.startsWith("accepted/")
    ) {
      throw new Error(`K0-06 accepted analysis differs: ${fixtureId}`);
    }
  }
  for (const fixtureId of EXTRACTION_REJECTION_CLASSES) {
    const analysis = candidate.analyze(fixtureId);
    const expected = EXTRACTION_DIAGNOSTIC_EXPECTATIONS[fixtureId];
    if (
      !analysis.diagnostic ||
      analysis.diagnostic.id !== expected.id ||
      analysis.diagnostic.severity !== expected.severity ||
      analysis.diagnostic.message !== expected.message ||
      analysis.diagnostic.explanation !== expected.explanation ||
      analysis.diagnostic.correction !== expected.correction ||
      analysis.diagnostic.source !== `rejected/${fixtureId}.ts` ||
      analysis.diagnostic.range.line < 1 ||
      analysis.diagnostic.range.column < 1 ||
      analysis.diagnostic.range.length < 1
    ) {
      throw new Error(`K0-06 rejected analysis differs: ${fixtureId}`);
    }
    const rejectedOutput = join(temporary, "rejected", fixtureId);
    try {
      emitAcceptedHandler(analysis, rejectedOutput);
      throw new Error(`K0-06 rejected emission started: ${fixtureId}`);
    } catch (error: unknown) {
      if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
    }
  }

  const firstRoot = join(temporary, "first");
  const secondRoot = join(temporary, "second");
  for (const fixtureId of EXTRACTION_ACCEPTED_CLASSES) {
    emitAcceptedHandler(candidate.analyze(fixtureId), firstRoot);
    emitAcceptedHandler(candidate.analyze(fixtureId), secondRoot);
  }
  const firstFiles = readdirSync(firstRoot).sort();
  const secondFiles = readdirSync(secondRoot).sort();
  if (JSON.stringify(firstFiles) !== JSON.stringify(secondFiles)) {
    throw new Error("K0-06 generated file inventories differ");
  }
  for (const file of firstFiles) {
    const first = readFileSync(join(firstRoot, file));
    const second = readFileSync(join(secondRoot, file));
    if (!first.equals(second)) throw new Error(`K0-06 generated bytes differ: ${file}`);
    const source = first.toString("utf8");
    if (
      scanImports(source).length !== 0 ||
      /(?:fragment|hydrate|component-runtime|server-only)/u.test(source)
    ) {
      throw new Error(`K0-06 generated handler graph differs: ${file}`);
    }
  }

  const containmentRoot = join(temporary, "contained");
  mkdirSync(containmentRoot);
  for (const destination of [
    join(containmentRoot, "../escape.js"),
    join(containmentRoot, "..", "outside", "escape.js"),
  ]) {
    try {
      assertContainedOutput(containmentRoot, destination);
      throw new Error("K0-06 traversal output was accepted");
    } catch (error: unknown) {
      if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
    }
  }
  const outside = join(temporary, "outside");
  mkdirSync(outside, { recursive: true });
  symlinkSync(outside, join(containmentRoot, "linked"), "dir");
  try {
    assertContainedOutput(containmentRoot, join(containmentRoot, "linked/escape.js"));
    throw new Error("K0-06 symlink output was accepted");
  } catch (error: unknown) {
    if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
  }
  const linkedRoot = join(temporary, "linked-root");
  symlinkSync(outside, linkedRoot, "dir");
  try {
    assertContainedOutput(linkedRoot, join(linkedRoot, "escape.js"));
    throw new Error("K0-06 symlink output root was accepted");
  } catch (error: unknown) {
    if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
  }
  const linkedAncestor = join(temporary, "linked-ancestor");
  symlinkSync(outside, linkedAncestor, "dir");
  const nestedLinkedRoot = join(linkedAncestor, "not-created");
  try {
    assertContainedOutput(nestedLinkedRoot, join(nestedLinkedRoot, "escape.js"));
    throw new Error("K0-06 symlink output ancestor was accepted");
  } catch (error: unknown) {
    if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
  }
  const intermediateTarget = join(outside, "existing");
  mkdirSync(intermediateTarget);
  const intermediateLink = join(temporary, "intermediate-link");
  symlinkSync(outside, intermediateLink, "dir");
  const intermediateRoot = join(intermediateLink, "existing", "not-created");
  try {
    assertContainedOutput(intermediateRoot, join(intermediateRoot, "escape.js"));
    throw new Error("K0-06 intermediate symlink output ancestor was accepted");
  } catch (error: unknown) {
    if (error instanceof Error && error.message.startsWith("K0-06")) throw error;
  }
  }
  finally {
    candidate[Symbol.dispose]();
  }
} finally {
  rmSync(temporary, { recursive: true, force: true });
}

const metamorphic = mkdtempSync(join(realpathSync(tmpdir()), "fadeno-extraction-metamorphic-"));
try {
  writeFileSync(join(metamorphic, "tsconfig.json"), `${JSON.stringify({
    compilerOptions: { strict: true, target: "ES2022", module: "ES2022" },
    include: ["*.ts"],
  })}\n`);
  writeFileSync(join(metamorphic, "server-only.d.ts"), [
    'declare module "server-only:secrets" { export const secret: string; }',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "renamed-barrel.ts"), [
    'export { secret as renamed } from "server-only:secrets";',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "renamed-handler.ts"), [
    'import { renamed as arbitraryValue } from "./renamed-barrel.ts";',
    "export function arbitraryName(arbitraryParameter: HTMLElement): void {",
    "  arbitraryParameter.textContent = arbitraryValue;",
    "}",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "opaque-one.ts"), [
    "const firstRenamedValue = new AbortController();",
    "export function first(): void { firstRenamedValue.abort(); }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "opaque-two.ts"), [
    "",
    "",
    "const secondRenamedValue = new AbortController();",
    "export function second(renamedParameter: string): void {",
    "  if (renamedParameter) secondRenamedValue.abort();",
    "}",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "call-result.ts"), [
    "function createCapability(): object { return {}; }",
    "const renamedCallResult = createCapability();",
    "export function use(): void { void renamedCallResult; }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "unresolved.ts"), [
    'import { missing } from "./absent.ts";',
    "export function use(): void { void missing; }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "server-call-barrel.ts"), [
    'export { execute as renamedServerCall } from "server-only:capability";',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "server-call.d.ts"), [
    'declare module "server-only:capability" { export function execute(): void; }',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "safe.ts"), [
    "export function safe(): void {}",
    "export const safeValue = 1;",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "closure-cases.ts"), [
    'import { renamed as serverValue } from "./renamed-barrel.ts";',
    'import { renamedServerCall } from "./server-call-barrel.ts";',
    'import * as serverNamespace from "./server-call-barrel.ts";',
    'import { safe } from "./safe.ts";',
    'import { safeValue } from "./safe.ts";',
    'import * as safeNamespace from "./safe.ts";',
    'import { safe as extraSafe } from "./safe-extra.ts";',
    'function localHelper(): void {}',
    'export const server = () => { renamedServerCall(); safe(); };',
    'export const serverValueReference = (output: HTMLElement) => { output.textContent = serverValue; safe(); };',
    'export const serverNamespaceCall = () => { serverNamespace.renamedServerCall(); safe(); };',
    'export const random = () => { Math.random(); safe(); };',
    'export const timer = () => { setInterval(() => {}, 1); safe(); };',
    'export const opaque = () => { new AbortController(); safe(); };',
    'export const ambient = () => { window.alert("unsafe"); safe(); };',
    'const moduleName = "./safe.ts";',
    'export const dynamic = async () => { await import(moduleName); safe(); };',
    'export const safeOnly = () => { safe(); };',
    'export const sameSourceHelper = () => { localHelper(); safe(); };',
    'export const extraImportedHelper = () => { extraSafe(); safe(); };',
    'export const unresolvedValue = () => { void missingRuntimeValue; safe(); };',
    'export const importedValue = () => { void safeValue; safe(); };',
    'export const namespaceValue = () => { void safeNamespace.safeValue; safe(); };',
    'export function outer(rootParameter: string) { return () => { void rootParameter; safe(); }; }',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "safe-extra.ts"), [
    "export function safe(): void {}",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "behavior-with-helper.ts"), [
    'import { safe } from "./safe.ts";',
    "export function behavior(): void { safe(); }",
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "capture-at.ts"), [
    'export const value = "x".repeat(65534);',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "capture-over.ts"), [
    'export const value = "x".repeat(65535);',
    "",
  ].join("\n"));
  writeFileSync(join(metamorphic, "capture-values.ts"), [
    'const at = "x".repeat(65534);',
    'const over = "x".repeat(65535);',
    'const multibyte = "界".repeat(21845);',
    'const nested = Object.freeze({ a: Object.freeze(["界", -1, true, null]) });',
    'const unknown = createValue();',
    'const envelopeAt = "x".repeat(65524);',
    'const envelopeOver = "x".repeat(65525);',
    'const multiA = "x".repeat(32760);',
    'const multiB = "x".repeat(32760);',
    'const huge = "x".repeat(1000000000);',
    "const nonFinite = 1e309;",
    "const negativeZero = -0;",
    'const prototypeKey = { "__proto__": 1 };',
    'const constructorKey = { constructor: 1 };',
    'const nestedPrototypeKey = { safe: { prototype: 1 } };',
    'declare function createValue(): unknown;',
    "",
  ].join("\n"));
  const api = new API({ cwd: metamorphic });
  try {
    const projectPath = join(metamorphic, "tsconfig.json");
    const project = api.updateSnapshot({
      openProjects: [{ uri: new URL(`file://${projectPath}`).href }],
    }).getProjects()[0];
    if (!project) throw new Error("K0-06 metamorphic TypeScript project is absent");
    const source = (name: string) => {
      const file = project.program.getSourceFile({ uri: new URL(`file://${join(metamorphic, name)}`).href });
      if (!file) throw new Error(`K0-06 metamorphic source is absent: ${name}`);
      return file;
    };
    const indirect = classifyReachableModule(project, source("renamed-handler.ts"));
    if (indirect?.id !== "FADENO_K0_EXTRACT_SERVER_IMPORT") {
      throw new Error("K0-06 indirect server flow was accepted");
    }
    const first = classifyModule(source("opaque-one.ts"));
    const second = classifyModule(source("opaque-two.ts"));
    if (
      first?.id !== "FADENO_K0_EXTRACT_OPAQUE_CAPTURE" ||
      second?.id !== first.id ||
      second.range.line === first.range.line
    ) {
      throw new Error("K0-06 renamed/source-shifted opaque flow differs");
    }
    if (
      classifyModule(source("call-result.ts"))?.id !== "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW" ||
      classifyReachableModule(project, source("unresolved.ts"))?.id !==
        "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW"
    ) {
      throw new Error("K0-06 ambiguous flow was accepted");
    }
    const closureSource = source("closure-cases.ts");
    const closure = (name: string) => {
      const statement = closureSource.statements.find((item) =>
        ast.isVariableStatement(item) &&
        ast.isIdentifier(item.declarationList.declarations[0]?.name) &&
        item.declarationList.declarations[0]?.name.text === name
      );
      const initializer = statement && ast.isVariableStatement(statement)
        ? statement.declarationList.declarations[0]?.initializer
        : undefined;
      if (!initializer) throw new Error(`K0-06 closure case is absent: ${name}`);
      return initializer;
    };
    const closureExpectations = {
      server: "FADENO_K0_EXTRACT_SERVER_IMPORT",
      serverValueReference: "FADENO_K0_EXTRACT_SERVER_IMPORT",
      serverNamespaceCall: "FADENO_K0_EXTRACT_SERVER_IMPORT",
      random: "FADENO_K0_EXTRACT_NON_DETERMINISTIC_CAPTURE",
      timer: "FADENO_K0_EXTRACT_ASYNC_LIFETIME",
      opaque: "FADENO_K0_EXTRACT_OPAQUE_CAPTURE",
      ambient: "FADENO_K0_EXTRACT_AMBIENT_CAPTURE",
      dynamic: "FADENO_K0_EXTRACT_DYNAMIC_IMPORT",
      sameSourceHelper: "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW",
      extraImportedHelper: "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW",
      unresolvedValue: "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW",
      importedValue: "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW",
      namespaceValue: "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW",
    } as const;
    for (const [name, expected] of Object.entries(closureExpectations)) {
      if (classifySelectedClosure(project, closureSource, closure(name))?.id !== expected) {
        throw new Error(`K0-06 selected closure flow was accepted: ${name}`);
      }
    }
    if (classifySelectedClosure(project, closureSource, closure("safeOnly")) !== undefined) {
      throw new Error("K0-06 single permitted behavior dependency was refused");
    }
    const outer = closureSource.statements.find((item) =>
      ast.isFunctionDeclaration(item) && item.name?.text === "outer"
    );
    const returnedClosure = outer && ast.isFunctionDeclaration(outer)
      ? outer.body?.statements.find(ast.isReturnStatement)?.expression
      : undefined;
    if (
      !returnedClosure ||
      classifySelectedClosure(project, closureSource, returnedClosure)?.id !==
        "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW"
    ) throw new Error("K0-06 root parameter capture was accepted");
    const safeSource = source("safe.ts");
    const safeDeclaration = safeSource.statements.find(ast.isFunctionDeclaration);
    if (
      !safeDeclaration ||
      classifySelectedClosure(project, safeSource, safeDeclaration, {
        allowedExternalFunctions: 0,
      }) !== undefined
    ) throw new Error("K0-06 self-contained behavior was refused");
    const behaviorWithHelper = source("behavior-with-helper.ts").statements.find(
      ast.isFunctionDeclaration,
    );
    if (
      !behaviorWithHelper ||
      classifySelectedClosure(
        project,
        source("behavior-with-helper.ts"),
        behaviorWithHelper,
        { allowedExternalFunctions: 0 },
      )?.id !== "FADENO_K0_EXTRACT_AMBIGUOUS_FLOW"
    ) throw new Error("K0-06 behavior dependency graph was accepted without emission");
    if (
      classifyModule(source("capture-at.ts")) !== undefined ||
      classifyModule(source("capture-over.ts"))?.id !== "FADENO_K0_EXTRACT_CAPTURE_SIZE"
    ) throw new Error("K0-06 serialized capture boundary differs");
    const captureSource = source("capture-values.ts");
    const capture = (name: string) => {
      const statement = captureSource.statements.find((item) =>
        ast.isVariableStatement(item) &&
        ast.isIdentifier(item.declarationList.declarations[0]?.name) &&
        item.declarationList.declarations[0]?.name.text === name
      );
      const initializer = statement && ast.isVariableStatement(statement)
        ? statement.declarationList.declarations[0]?.initializer
        : undefined;
      if (!initializer) throw new Error(`K0-06 capture case is absent: ${name}`);
      return measurePlainCapture(initializer);
    };
    if (
      capture("at") !== 65_536 || capture("over") !== 65_537 ||
      (capture("multibyte") ?? 0) <= 65_536 ||
      capture("nested") !== Buffer.byteLength(JSON.stringify({ a: ["界", -1, true, null] })) ||
      capture("unknown") !== undefined || capture("nonFinite") !== undefined ||
      capture("negativeZero") !== undefined || capture("prototypeKey") !== undefined ||
      capture("constructorKey") !== undefined || capture("nestedPrototypeKey") !== undefined
    ) throw new Error("K0-06 serialized capture measurement differs");
    const initializer = (name: string) => {
      const statement = captureSource.statements.find((item) =>
        ast.isVariableStatement(item) &&
        ast.isIdentifier(item.declarationList.declarations[0]?.name) &&
        item.declarationList.declarations[0]?.name.text === name
      );
      const value = statement && ast.isVariableStatement(statement)
        ? statement.declarationList.declarations[0]?.initializer
        : undefined;
      if (!value) throw new Error(`K0-06 capture initializer is absent: ${name}`);
      return value;
    };
    if (
      measureCaptureEnvelope([["value", initializer("envelopeAt")]]) !== 65_536 ||
      measureCaptureEnvelope([["value", initializer("envelopeOver")]]) !== 65_537 ||
      measureCaptureEnvelope([
        ["a", initializer("multiA")],
        ["b", initializer("multiB")],
      ]) !== Buffer.byteLength(JSON.stringify({
        a: "x".repeat(32_760),
        b: "x".repeat(32_760),
      })) ||
      measureCaptureEnvelope([["value", initializer("huge")]]) !== 65_537 ||
      measureCaptureEnvelope([["__proto__", initializer("multiA")]]) !== undefined ||
      measureCaptureEnvelope([["constructor", initializer("multiA")]]) !== undefined
    ) throw new Error("K0-06 serialized capture envelope differs");
  } finally {
    api.close();
  }
} finally {
  rmSync(metamorphic, { recursive: true, force: true });
}

console.log(
  `extraction candidate contract passed (${EXTRACTION_ACCEPTED_CLASSES.length} accepted, ${EXTRACTION_REJECTION_CLASSES.length} rejected, ${Object.keys(EXTRACTION_ROOT_EXPORTS).length} roots)`,
);
