import { createHash, randomUUID } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

import type { FadenoConfig } from "../../index.ts";
import { FadenoDiagnosticError } from "../diagnostic.ts";
import {
  assertRouteManifestSemantics,
  discoverRouteManifest,
  stableRouteManifest,
  type RouteManifest,
  type RouteSegment,
} from "./discovery.ts";

const GENERATOR_VERSION = 1;
const OUTPUT_FILES = ["index.d.ts", "index.js", "manifest.json", "owner.json"] as const;

export type GenerationFailurePoint = "manifest" | "runtime" | "declaration" | "owner" | "beforeReplace";
export type RouteGenerationResult = Readonly<{
  changed: boolean;
  output: string;
  sourceSha256: string;
}>;

function sha256(bytes: string | Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function fail(code: string): never {
  throw new FadenoDiagnosticError(
    `FADENO_GENERATION_${code}`,
    `Route generation violation: ${code.toLowerCase().replaceAll("_", " ")}`,
    [".fadeno/routes"],
    `https://fadeno.dev/diagnostics/generation/${code.toLowerCase().replaceAll("_", "-")}`,
    "Correct the route source or generated-output ownership issue and run fadeno check again.",
  );
}

function renderRuntime(manifest: RouteManifest): string {
  const definitions = Object.fromEntries(manifest.routes.map(({ id, segments }) => [id, segments]));
  return [
    `// Generated by Fadeno routes v${GENERATOR_VERSION}; source ${manifest.generation.sourceSha256}.`,
    "// Do not edit. Import through the canonical fadeno:routes virtual module.",
    `const definitions = Object.freeze(${JSON.stringify(definitions)});`,
    "function refuse(code) { throw new TypeError(`FADENO_ROUTE_LINK_${code}`); }",
    "function plain(value) { if (typeof value !== 'object' || value === null || Array.isArray(value)) return false; const prototype = Object.getPrototypeOf(value); return prototype === Object.prototype || prototype === null; }",
    "function encode(value) { if (typeof value !== 'string' || value === '' || value === '.' || value === '..') refuse('PARAMETER'); try { return encodeURIComponent(value).replace(/[!'()*]/gu, (character) => `%${character.codePointAt(0).toString(16).toUpperCase()}`); } catch { refuse('PARAMETER'); } }",
    "export function routeHref(input) {",
    "  if (!plain(input) || typeof input.route !== 'string') refuse('INPUT');",
    "  if (!Object.hasOwn(definitions, input.route)) refuse('ROUTE');",
    "  const segments = definitions[input.route];",
    "  const expected = segments.filter((segment) => segment.kind !== 'static').map((segment) => segment.name);",
    "  const keys = Object.keys(input).sort();",
    "  if (keys.join('\\0') !== (expected.length === 0 ? 'route' : 'parameters\\0route')) refuse('INPUT');",
    "  const parameters = input.parameters;",
    "  if (expected.length > 0 && (!plain(parameters) || Object.keys(parameters).sort().join('\\0') !== [...expected].sort().join('\\0'))) refuse('PARAMETERS');",
    "  const output = [];",
    "  for (const segment of segments) {",
    "    if (segment.kind === 'static') output.push(segment.value);",
    "    else if (segment.kind === 'parameter') output.push(encode(parameters[segment.name]));",
    "    else { const values = parameters[segment.name]; if (!Array.isArray(values) || values.length === 0) refuse('PARAMETER'); output.push(...values.map(encode)); }",
    "  }",
    "  return output.length === 0 ? '/' : `/${output.join('/')}`;",
    "}",
    "",
  ].join("\n");
}

function parameterType(segment: RouteSegment): string {
  return segment.kind === "rest" ? "readonly [string, ...string[]]" : "string";
}

function renderDeclaration(manifest: RouteManifest): string {
  const members = manifest.routes.map(({ id, segments }) => {
    const parameters = segments.filter((segment) => segment.kind !== "static");
    const value = parameters.length === 0
      ? "never"
      : `{ ${parameters.map((segment) => `readonly ${JSON.stringify(segment.name)}: ${parameterType(segment)}`).join("; ")} }`;
    return `    readonly ${JSON.stringify(id)}: ${value};`;
  });
  return [
    `// Generated by Fadeno routes v${GENERATOR_VERSION}; source ${manifest.generation.sourceSha256}.`,
    "// Do not edit.",
    "declare module \"fadeno:routes\" {",
    "  interface RouteDefinitionMap {",
    ...members,
    "  }",
    "  export type RouteId = Extract<keyof RouteDefinitionMap, string>;",
    "  export type RouteParameters<Id extends RouteId> = RouteDefinitionMap[Id];",
    "  export type RouteHrefInput<Id extends RouteId = RouteId> = {",
    "    readonly [Current in Id]: RouteParameters<Current> extends never",
    "      ? { readonly route: Current }",
    "      : { readonly route: Current; readonly parameters: RouteParameters<Current> };",
    "  }[Id];",
    "  type NoExtra<Actual, Expected> = Actual & Record<Exclude<keyof Actual, keyof Expected>, never>;",
    "  type ExactRouteHrefInput<Input extends RouteHrefInput> = Input extends { readonly route: infer Id extends RouteId }",
    "    ? RouteParameters<Id> extends never",
    "      ? NoExtra<Input, { readonly route: Id }>",
    "      : Input extends { readonly parameters: infer Parameters extends RouteParameters<Id> }",
    "        ? NoExtra<Input, { readonly route: Id; readonly parameters: Parameters }> & { readonly parameters: NoExtra<Parameters, RouteParameters<Id>> }",
    "        : never",
    "    : never;",
    "  export function routeHref<const Input extends RouteHrefInput>(input: ExactRouteHrefInput<Input>): string;",
    "}",
    "",
  ].join("\n");
}

function ownerDocument(manifest: RouteManifest, files: Readonly<Record<string, string>>): string {
  return `${JSON.stringify({
    schemaVersion: 1,
    owner: "fadeno-routes",
    generatorVersion: GENERATOR_VERSION,
    sourceSha256: manifest.generation.sourceSha256,
    files: Object.entries(files).sort(([left], [right]) => compareText(left, right)).map(([path, bytes]) => ({ path, sha256: sha256(bytes) })),
  }, null, 2)}\n`;
}

function assertOwnedOutput(output: string): void {
  if (!existsSync(output)) return;
  if (lstatSync(output).isSymbolicLink() || !lstatSync(output).isDirectory()) fail("OUTPUT_TYPE");
  const entries = readdirSync(output).sort(compareText);
  if (JSON.stringify(entries) !== JSON.stringify([...OUTPUT_FILES].sort(compareText))) fail("OUTPUT_UNOWNED");
  let owner: { owner?: string; generatorVersion?: number; sourceSha256?: string; files?: readonly { path?: string; sha256?: string }[] };
  try { owner = JSON.parse(readFileSync(join(output, "owner.json"), "utf8")); } catch { fail("OUTPUT_OWNER"); }
  if (owner.owner !== "fadeno-routes" || owner.generatorVersion !== GENERATOR_VERSION ||
      typeof owner.sourceSha256 !== "string" || !/^[a-f0-9]{64}$/u.test(owner.sourceSha256) || !Array.isArray(owner.files) ||
      JSON.stringify(owner.files.map(({ path }) => path).sort(compareText)) !== JSON.stringify(["index.d.ts", "index.js", "manifest.json"])) {
    fail("OUTPUT_OWNER");
  }
  for (const file of owner.files) {
    if (typeof file.path !== "string" || typeof file.sha256 !== "string" || !OUTPUT_FILES.includes(file.path as typeof OUTPUT_FILES[number]) ||
        sha256(readFileSync(join(output, file.path))) !== file.sha256) fail("OUTPUT_OWNER");
  }
  const manifest = JSON.parse(readFileSync(join(output, "manifest.json"), "utf8")) as RouteManifest;
  assertRouteManifestSemantics(manifest);
  if (manifest.generation.version !== owner.generatorVersion || manifest.generation.sourceSha256 !== owner.sourceSha256) fail("OUTPUT_IDENTITY");
  const identity = `Generated by Fadeno routes v${owner.generatorVersion}; source ${owner.sourceSha256}.`;
  if (!readFileSync(join(output, "index.js"), "utf8").includes(identity) || !readFileSync(join(output, "index.d.ts"), "utf8").includes(identity)) {
    fail("OUTPUT_IDENTITY");
  }
}

function assertOutputParent(projectRoot: string, parent: string): void {
  const containment = relative(resolve(projectRoot), resolve(parent));
  if (containment.startsWith("..") || containment.includes("..") || lstatSync(projectRoot).isSymbolicLink()) fail("OUTPUT_ESCAPE");
  if (existsSync(parent) && (lstatSync(parent).isSymbolicLink() || !lstatSync(parent).isDirectory())) fail("OUTPUT_PARENT");
  if (!existsSync(parent)) mkdirSync(parent);
}

export function generateRoutes(
  projectRoot: string,
  config: FadenoConfig,
  failurePoint?: GenerationFailurePoint,
  beforeSourceValidation?: () => void,
): RouteGenerationResult {
  if (!config.routes) fail("ROUTES_REQUIRED");
  const manifest = discoverRouteManifest(projectRoot, config.routes);
  assertRouteManifestSemantics(manifest);
  const manifestBytes = stableRouteManifest(manifest);
  const runtimeBytes = renderRuntime(manifest);
  const declarationBytes = renderDeclaration(manifest);
  const correlated = { "manifest.json": manifestBytes, "index.js": runtimeBytes, "index.d.ts": declarationBytes };
  const ownerBytes = ownerDocument(manifest, correlated);
  const expected: Readonly<Record<string, string>> = { ...correlated, "owner.json": ownerBytes };

  const parent = join(resolve(projectRoot), ".fadeno");
  const output = join(parent, "routes");
  assertOutputParent(projectRoot, parent);
  assertOwnedOutput(output);
  if (existsSync(output) && Object.entries(expected).every(([name, bytes]) => readFileSync(join(output, name), "utf8") === bytes)) {
    return { changed: false, output, sourceSha256: manifest.generation.sourceSha256 };
  }

  const pending = join(parent, `routes.pending-${randomUUID()}`);
  const previous = join(parent, `routes.previous-${randomUUID()}`);
  mkdirSync(pending);
  try {
    for (const [name, bytes, point] of [
      ["manifest.json", manifestBytes, "manifest"],
      ["index.js", runtimeBytes, "runtime"],
      ["index.d.ts", declarationBytes, "declaration"],
      ["owner.json", ownerBytes, "owner"],
    ] as const) {
      writeFileSync(join(pending, name), bytes);
      if (failurePoint === point) fail(`INJECTED_${point.toUpperCase()}`);
    }
    assertOwnedOutput(pending);
    const stagedManifest = JSON.parse(readFileSync(join(pending, "manifest.json"), "utf8")) as RouteManifest;
    assertRouteManifestSemantics(stagedManifest);
    beforeSourceValidation?.();
    const finalManifest = discoverRouteManifest(projectRoot, config.routes);
    if (finalManifest.generation.sourceSha256 !== manifest.generation.sourceSha256) fail("SOURCE_CHANGED");
    if (failurePoint === "beforeReplace") fail("INJECTED_BEFORE_REPLACE");
    assertOutputParent(projectRoot, parent);
    if (lstatSync(pending).isSymbolicLink() || !lstatSync(pending).isDirectory()) fail("OUTPUT_PENDING");

    const hadOutput = existsSync(output);
    if (hadOutput) renameSync(output, previous);
    try {
      renameSync(pending, output);
    } catch (error) {
      if (hadOutput && existsSync(previous)) renameSync(previous, output);
      throw error;
    }
    rmSync(previous, { recursive: true, force: true });
    return { changed: true, output, sourceSha256: manifest.generation.sourceSha256 };
  } finally {
    rmSync(pending, { recursive: true, force: true });
  }
}
