import { createHash, randomUUID } from "node:crypto";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

import type { FadenoConfig } from "../../index.ts";
import { FadenoDiagnosticError } from "../diagnostic.ts";
import {
  assertRouteManifestSemantics,
  discoverRouteManifest,
  stableRouteManifest,
  type RouteManifest,
  type RouteSegment,
} from "./discovery.ts";

const GENERATOR_VERSION = 1;
const OUTPUT_FILES = ["app.ts", "index.d.ts", "index.js", "manifest.json", "owner.json"] as const;

export type GenerationFailurePoint = "manifest" | "runtime" | "declaration" | "owner" | "beforeReplace";
export type GenerationOperationFailure = "afterBackup" | "replace" | "restore" | "cleanup";
export type RouteGenerationResult = Readonly<{
  changed: boolean;
  output: string;
  sourceSha256: string;
}>;

function sha256(bytes: string | Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function fail(code: string): never {
  throw new FadenoDiagnosticError(
    `FADENO_GENERATION_${code}`,
    `Route generation violation: ${code.toLowerCase().replaceAll("_", " ")}`,
    [".fadeno/routes"],
    `https://fadeno.dev/diagnostics/generation/${code.toLowerCase().replaceAll("_", "-")}`,
    "Correct the route source or generated-output ownership issue and run fadeno check again.",
  );
}

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function readManifest(path: string): RouteManifest {
  let value: unknown;
  try { value = JSON.parse(readFileSync(path, "utf8")); } catch { fail("OUTPUT_MANIFEST"); }
  if (!isPlainRecord(value) || !isPlainRecord(value["generation"]) || !Array.isArray(value["routes"])) fail("OUTPUT_MANIFEST");
  try { assertRouteManifestSemantics(value as RouteManifest); } catch (error) {
    if (error instanceof FadenoDiagnosticError) throw error;
    fail("OUTPUT_MANIFEST");
  }
  return value as RouteManifest;
}

function renderRuntime(manifest: RouteManifest): string {
  const definitions = Object.fromEntries(manifest.routes.map(({ id, segments }) => [id, segments]));
  return [
    `// Generated by Fadeno routes v${GENERATOR_VERSION}; source ${manifest.generation.sourceSha256}.`,
    "// Do not edit. Import through the canonical fadeno:routes virtual module.",
    `const definitions = Object.freeze(${JSON.stringify(definitions)});`,
    "function refuse(code) { throw new TypeError(`FADENO_ROUTE_LINK_${code}`); }",
    "function plain(value) { if (typeof value !== 'object' || value === null || Array.isArray(value)) return false; const prototype = Object.getPrototypeOf(value); return prototype === Object.prototype || prototype === null; }",
    "function encode(value) { if (typeof value !== 'string' || value === '' || value === '.' || value === '..') refuse('PARAMETER'); try { return encodeURIComponent(value).replace(/[!'()*]/gu, (character) => `%${character.codePointAt(0).toString(16).toUpperCase()}`); } catch { refuse('PARAMETER'); } }",
    "export function routeHref(input) {",
    "  if (!plain(input) || typeof input.route !== 'string') refuse('INPUT');",
    "  if (!Object.hasOwn(definitions, input.route)) refuse('ROUTE');",
    "  const segments = definitions[input.route];",
    "  const expected = segments.filter((segment) => segment.kind !== 'static').map((segment) => segment.name);",
    "  const keys = Object.keys(input).sort();",
    "  if (keys.join('\\0') !== (expected.length === 0 ? 'route' : 'parameters\\0route')) refuse('INPUT');",
    "  const parameters = input.parameters;",
    "  if (expected.length > 0 && (!plain(parameters) || Object.keys(parameters).sort().join('\\0') !== [...expected].sort().join('\\0'))) refuse('PARAMETERS');",
    "  const output = [];",
    "  for (const segment of segments) {",
    "    if (segment.kind === 'static') output.push(segment.value);",
    "    else if (segment.kind === 'parameter') output.push(encode(parameters[segment.name]));",
    "    else {",
    "      const values = parameters[segment.name];",
    "      if (!Array.isArray(values) || values.length === 0 || Object.keys(values).length !== values.length) refuse('PARAMETER');",
    "      for (let index = 0; index < values.length; index += 1) { if (!Object.hasOwn(values, index)) refuse('PARAMETER'); output.push(encode(values[index])); }",
    "    }",
    "  }",
    "  return output.length === 0 ? '/' : `/${output.join('/')}`;",
    "}",
    "",
  ].join("\n");
}

function parameterType(segment: RouteSegment): string {
  return segment.kind === "rest" ? "readonly [string, ...string[]]" : "string";
}

function renderDeclaration(manifest: RouteManifest): string {
  const parameterCases = manifest.routes.map(({ id, segments }) => {
    const parameters = segments.filter((segment) => segment.kind !== "static");
    const value = parameters.length === 0
      ? "never"
      : `{ ${parameters.map((segment) => `readonly ${JSON.stringify(segment.name)}: ${parameterType(segment)}`).join("; ")} }`;
    return `    Id extends ${JSON.stringify(id)} ? ${value} :`;
  });
  const routeIds = manifest.routes.map(({ id }) => JSON.stringify(id)).join(" | ") || "never";
  return [
    `// Generated by Fadeno routes v${GENERATOR_VERSION}; source ${manifest.generation.sourceSha256}.`,
    "// Do not edit.",
    "declare module \"fadeno:routes\" {",
    `  export type RouteId = ${routeIds};`,
    "  export type RouteParameters<Id extends RouteId> =",
    ...parameterCases,
    "    never;",
    "  export type RouteHrefInput<Id extends RouteId = RouteId> = {",
    "    readonly [Current in Id]: RouteParameters<Current> extends never",
    "      ? { readonly route: Current }",
    "      : { readonly route: Current; readonly parameters: RouteParameters<Current> };",
    "  }[Id];",
    "  export function routeHref<const Input extends RouteHrefInput>(",
    "    input: Input extends { readonly route: infer Id extends RouteId }",
    "    ? RouteParameters<Id> extends never",
    "      ? Input & Record<Exclude<keyof Input, \"route\">, never>",
    "      : Input extends { readonly parameters: infer Parameters extends RouteParameters<Id> }",
    "        ? Input & Record<Exclude<keyof Input, \"route\" | \"parameters\">, never> & {",
    "            readonly parameters: Parameters & Record<Exclude<keyof Parameters, keyof RouteParameters<Id>>, never>;",
    "          }",
    "        : never",
    "    : never",
    "  ): string;",
    "}",
    "",
  ].join("\n");
}

function renderApplication(manifest: RouteManifest): string {
  const sources = [...new Set(manifest.routes.flatMap((route) => [
    route.source,
    ...route.layouts,
    ...(route.notFound ? [route.notFound] : []),
    ...(route.error ? [route.error] : []),
  ]))].sort(compareText);
  const bindings = new Map(sources.map((source, index) => [source, `module${index}`]));
  const definitions = manifest.routes.map(({ id, segments }) => ({ id, segments }));
  const cases = manifest.routes.map((route) => {
    const source = bindings.get(route.source);
    if (!source) throw new TypeError("FADENO_GENERATION_APPLICATION_SOURCE");
    if (route.kind === "handler") return `    case ${JSON.stringify(route.id)}: return ${source}(request);`;
    const layouts = route.layouts.map((path) => bindings.get(path)).join(", ");
    const notFound = route.notFound ? bindings.get(route.notFound) : undefined;
    const error = route.error ? bindings.get(route.error) : undefined;
    return `    case ${JSON.stringify(route.id)}: return renderRoute({ request, parameters: selected.parameters, page: ${source}, layouts: [${layouts}], notFound: ${notFound ?? "undefined"}, error: ${error ?? "undefined"} });`;
  });
  const ownerDepth = (source: string, role: string): number => {
    const prefix = `${manifest.root}/`;
    const suffix = `/${role}`;
    if (!source.startsWith(prefix) || !source.endsWith(suffix)) throw new TypeError("FADENO_GENERATION_APPLICATION_OWNER");
    const directory = source.slice(prefix.length, -suffix.length);
    return directory === "" ? 0 : directory.split("/").length;
  };
  const fallbackBySource = new Map<string, RouteManifest["routes"][number]>();
  for (const route of manifest.routes) {
    if (route.notFound && !fallbackBySource.has(route.notFound)) fallbackBySource.set(route.notFound, route);
  }
  const fallbacks = [...fallbackBySource].map(([source, route], index) => {
    const depth = ownerDepth(source, "not-found.tsx");
    const layouts = route.layouts.filter((path) => ownerDepth(path, "layout.tsx") <= depth);
    const error = route.error && ownerDepth(route.error, "error.tsx") <= depth ? route.error : null;
    return { id: `fallback${index}`, segments: route.segments.slice(0, depth), source, layouts, error };
  }).sort((left, right) => right.segments.length - left.segments.length || compareText(left.source, right.source));
  const fallbackDefinitions = fallbacks.map(({ id, segments }) => ({ id, segments }));
  const fallbackCases = fallbacks.map((fallback) =>
    `    case ${JSON.stringify(fallback.id)}: return renderRoute({ request, parameters: selectedFallback.parameters, page: () => notFound(), layouts: [${fallback.layouts.map((path) => bindings.get(path)).join(", ")}], notFound: ${bindings.get(fallback.source)}, error: ${fallback.error ? bindings.get(fallback.error) : "undefined"} });`);
  return [
    `// Generated by Fadeno application v${GENERATOR_VERSION}; source ${manifest.generation.sourceSha256}.`,
    "// Do not edit. This binding is correlated with manifest.json.",
    'import { notFound, renderRoute, type Handler } from "fadeno-framework-internal";',
    ...sources.map((source) => `import ${bindings.get(source)} from ${JSON.stringify(`../../${source}`)};`),
    "",
    "type Segment = Readonly<{ kind: 'static'; value: string }> | Readonly<{ kind: 'parameter' | 'rest'; name: string }> ;",
    `const definitions: readonly Readonly<{ id: string; segments: readonly Segment[] }>[] = Object.freeze(${JSON.stringify(definitions)});`,
    `const fallbackDefinitions: readonly Readonly<{ id: string; segments: readonly Segment[] }>[] = Object.freeze(${JSON.stringify(fallbackDefinitions)});`,
    "function decode(value: string): string | undefined {",
    "  if ([...value].some((character) => { const point = character.codePointAt(0)!; return point < 0x21 || point > 0x7e || '\\\\/?#'.includes(character); })) return undefined;",
    "  try { const result = decodeURIComponent(value); return result === '' || result === '.' || result === '..' ? undefined : result; } catch { return undefined; }",
    "}",
    "function match(pathname: string): { id: string; parameters: Readonly<Record<string, string | readonly string[]>> } | undefined {",
    "  if (pathname !== '/' && (!pathname.startsWith('/') || pathname.endsWith('/') || pathname.includes('//'))) return undefined;",
    "  const encoded = pathname === '/' ? [] : pathname.slice(1).split('/'); const decoded: string[] = [];",
    "  for (const part of encoded) { const value = decode(part); if (value === undefined) return undefined; decoded.push(value); }",
    "  let selected: { id: string; parameters: Readonly<Record<string, string | readonly string[]>>; rank: readonly number[] } | undefined;",
    "  for (const definition of definitions) { const parameters = Object.create(null) as Record<string, string | readonly string[]>; const rank: number[] = []; let index = 0; let valid = true;",
    "    for (const segment of definition.segments) { if (segment.kind === 'rest') { if (index >= decoded.length) { valid = false; break; } parameters[segment.name!] = Object.freeze(decoded.slice(index)); rank.push(1); index = decoded.length; continue; } if (index >= decoded.length) { valid = false; break; } if (segment.kind === 'static') { if (encoded[index]! !== segment.value) { valid = false; break; } rank.push(3); } else { parameters[segment.name!] = decoded[index]!; rank.push(2); } index += 1; }",
    "    if (!valid || index !== decoded.length) continue; let better = selected === undefined; for (let position = 0; !better && position < Math.max(rank.length, selected?.rank.length ?? 0); position += 1) { const difference = (rank[position] ?? 0) - (selected?.rank[position] ?? 0); if (difference !== 0) { better = difference > 0; break; } } if (better) selected = { id: definition.id, parameters: Object.freeze(parameters), rank: Object.freeze(rank) };",
    "  }",
    "  return selected;",
    "}",
    "function matchFallback(pathname: string): { id: string; parameters: Readonly<Record<string, string | readonly string[]>> } | undefined {",
    "  if (pathname !== '/' && (!pathname.startsWith('/') || pathname.includes('//'))) return undefined; const encoded = pathname === '/' ? [] : pathname.replace(/\\/$/u, '').slice(1).split('/'); const decoded: string[] = [];",
    "  for (const part of encoded) { const value = decode(part); if (value === undefined) return undefined; decoded.push(value); }",
    "  for (const definition of fallbackDefinitions) { const parameters = Object.create(null) as Record<string, string | readonly string[]>; let index = 0; let valid = true; for (const segment of definition.segments) { if (segment.kind === 'rest') { if (index >= decoded.length) { valid = false; break; } parameters[segment.name] = Object.freeze(decoded.slice(index)); index = decoded.length; break; } if (index >= decoded.length) { valid = false; break; } if (segment.kind === 'static') { if (encoded[index]! !== segment.value) { valid = false; break; } } else { parameters[segment.name] = decoded[index]!; } index += 1; } if (valid) return { id: definition.id, parameters: Object.freeze(parameters) }; }",
    "  return undefined;",
    "}",
    "export const handler: Handler = async (request) => {",
    "  const pathname = new URL(request.url).pathname; const selected = match(pathname);",
    "  if (!selected) { const selectedFallback = matchFallback(pathname); if (!selectedFallback) return renderRoute({ request, parameters: Object.freeze(Object.create(null) as Record<string, never>), page: () => notFound(), layouts: [] }); switch (selectedFallback.id) {",
    ...fallbackCases,
    "    default: throw new TypeError('FADENO_GENERATED_FALLBACK_ID');",
    "  } }",
    "  switch (selected.id) {",
    ...cases,
    "    default: throw new TypeError('FADENO_GENERATED_ROUTE_ID');",
    "  }",
    "};",
    "",
  ].join("\n");
}

function ownerDocument(manifest: RouteManifest, files: Readonly<Record<string, string>>): string {
  return `${JSON.stringify({
    schemaVersion: 1,
    owner: "fadeno-routes",
    generatorVersion: GENERATOR_VERSION,
    sourceSha256: manifest.generation.sourceSha256,
    files: Object.entries(files).sort(([left], [right]) => compareText(left, right)).map(([path, bytes]) => ({ path, sha256: sha256(bytes) })),
  }, null, 2)}\n`;
}

function assertOwnedOutput(output: string): void {
  if (!existsSync(output)) return;
  if (lstatSync(output).isSymbolicLink() || !lstatSync(output).isDirectory()) fail("OUTPUT_TYPE");
  const entries = readdirSync(output).sort(compareText);
  if (JSON.stringify(entries) !== JSON.stringify([...OUTPUT_FILES].sort(compareText))) fail("OUTPUT_UNOWNED");
  for (const name of OUTPUT_FILES) {
    const status = lstatSync(join(output, name));
    if (status.isSymbolicLink() || !status.isFile()) fail("OUTPUT_CHILD_TYPE");
  }
  let ownerValue: unknown;
  try { ownerValue = JSON.parse(readFileSync(join(output, "owner.json"), "utf8")); } catch { fail("OUTPUT_OWNER"); }
  if (!isPlainRecord(ownerValue)) fail("OUTPUT_OWNER");
  const owner = ownerValue as { schemaVersion?: number; owner?: string; generatorVersion?: number; sourceSha256?: string; files?: readonly unknown[] };
  if (JSON.stringify(Object.keys(owner).sort(compareText)) !== JSON.stringify(["files", "generatorVersion", "owner", "schemaVersion", "sourceSha256"]) ||
      owner.schemaVersion !== 1 || owner.owner !== "fadeno-routes" || owner.generatorVersion !== GENERATOR_VERSION ||
      typeof owner.sourceSha256 !== "string" || !/^[a-f0-9]{64}$/u.test(owner.sourceSha256) || !Array.isArray(owner.files)) {
    fail("OUTPUT_OWNER");
  }
  const ownerFiles: { path: string; sha256: string }[] = [];
  for (const fileValue of owner.files) {
    if (!isPlainRecord(fileValue)) fail("OUTPUT_OWNER");
    const file = fileValue as { path?: unknown; sha256?: unknown };
    if (JSON.stringify(Object.keys(file).sort(compareText)) !== JSON.stringify(["path", "sha256"]) ||
        typeof file.path !== "string" || typeof file.sha256 !== "string" || !OUTPUT_FILES.includes(file.path as typeof OUTPUT_FILES[number]) ||
        sha256(readFileSync(join(output, file.path))) !== file.sha256) fail("OUTPUT_OWNER");
    ownerFiles.push({ path: file.path, sha256: file.sha256 });
  }
  if (JSON.stringify(ownerFiles.map(({ path }) => path).sort(compareText)) !== JSON.stringify(["app.ts", "index.d.ts", "index.js", "manifest.json"])) fail("OUTPUT_OWNER");
  const manifest = readManifest(join(output, "manifest.json"));
  if (manifest.generation.version !== owner.generatorVersion || manifest.generation.sourceSha256 !== owner.sourceSha256) fail("OUTPUT_IDENTITY");
  const identity = `Generated by Fadeno routes v${owner.generatorVersion}; source ${owner.sourceSha256}.`;
  if (!readFileSync(join(output, "index.js"), "utf8").includes(identity) || !readFileSync(join(output, "index.d.ts"), "utf8").includes(identity)) {
    fail("OUTPUT_IDENTITY");
  }
  const applicationIdentity = `Generated by Fadeno application v${owner.generatorVersion}; source ${owner.sourceSha256}.`;
  if (!readFileSync(join(output, "app.ts"), "utf8").includes(applicationIdentity)) fail("OUTPUT_IDENTITY");
}

function assertOutputParent(projectRoot: string, parent: string): void {
  const containment = relative(resolve(projectRoot), resolve(parent));
  if (containment.startsWith("..") || containment.includes("..") || lstatSync(projectRoot).isSymbolicLink()) fail("OUTPUT_ESCAPE");
  if (existsSync(parent) && (lstatSync(parent).isSymbolicLink() || !lstatSync(parent).isDirectory())) fail("OUTPUT_PARENT");
  if (!existsSync(parent)) mkdirSync(parent);
}

function recoverPreviousOutput(parent: string, output: string): void {
  const previous = readdirSync(parent).filter((name) => name.startsWith("routes.previous-")).sort(compareText);
  if (previous.length > 1) fail("OUTPUT_RECOVERY_AMBIGUOUS");
  const candidate = previous[0];
  if (!candidate) return;
  const path = join(parent, candidate);
  assertOwnedOutput(path);
  if (existsSync(output)) rmSync(path, { recursive: true });
  else renameSync(path, output);
}

export function generateRoutes(
  projectRoot: string,
  config: FadenoConfig,
  failurePoint?: GenerationFailurePoint,
  beforeSourceValidation?: () => void,
  operationFailure?: GenerationOperationFailure,
  afterReplaceValidation?: () => void,
): RouteGenerationResult {
  if (!config.routes) fail("ROUTES_REQUIRED");
  const manifest = discoverRouteManifest(projectRoot, config.routes);
  assertRouteManifestSemantics(manifest);
  const manifestBytes = stableRouteManifest(manifest);
  const runtimeBytes = renderRuntime(manifest);
  const declarationBytes = renderDeclaration(manifest);
  const applicationBytes = renderApplication(manifest);
  const correlated = { "app.ts": applicationBytes, "manifest.json": manifestBytes, "index.js": runtimeBytes, "index.d.ts": declarationBytes };
  const ownerBytes = ownerDocument(manifest, correlated);
  const expected: Readonly<Record<string, string>> = { ...correlated, "owner.json": ownerBytes };

  const parent = join(resolve(projectRoot), ".fadeno");
  const output = join(parent, "routes");
  assertOutputParent(projectRoot, parent);
  recoverPreviousOutput(parent, output);
  assertOwnedOutput(output);
  if (existsSync(output) && Object.entries(expected).every(([name, bytes]) => readFileSync(join(output, name), "utf8") === bytes)) {
    return { changed: false, output, sourceSha256: manifest.generation.sourceSha256 };
  }

  const pending = join(parent, `routes.pending-${randomUUID()}`);
  const previous = join(parent, `routes.previous-${randomUUID()}`);
  mkdirSync(pending);
  try {
    for (const [name, bytes, point] of [
      ["manifest.json", manifestBytes, "manifest"],
      ["app.ts", applicationBytes, "runtime"],
      ["index.js", runtimeBytes, "runtime"],
      ["index.d.ts", declarationBytes, "declaration"],
      ["owner.json", ownerBytes, "owner"],
    ] as const) {
      writeFileSync(join(pending, name), bytes);
      if (failurePoint === point) fail(`INJECTED_${point.toUpperCase()}`);
    }
    assertOwnedOutput(pending);
    readManifest(join(pending, "manifest.json"));
    beforeSourceValidation?.();
    const finalManifest = discoverRouteManifest(projectRoot, config.routes);
    if (finalManifest.generation.sourceSha256 !== manifest.generation.sourceSha256) fail("SOURCE_CHANGED");
    if (failurePoint === "beforeReplace") fail("INJECTED_BEFORE_REPLACE");
    assertOutputParent(projectRoot, parent);
    assertOwnedOutput(pending);
    if (existsSync(output)) assertOwnedOutput(output);

    const hadOutput = existsSync(output);
    if (hadOutput) renameSync(output, previous);
    try {
      if (operationFailure === "afterBackup") fail("INJECTED_AFTER_BACKUP");
      if (operationFailure === "replace" || operationFailure === "restore") fail("INJECTED_REPLACE");
      renameSync(pending, output);
    } catch (error) {
      if (hadOutput && existsSync(previous)) {
        try {
          if (operationFailure === "restore") fail("INJECTED_RESTORE");
          renameSync(previous, output);
        } catch {
          if (!existsSync(output) && existsSync(previous)) renameSync(previous, output);
        }
      }
      throw error;
    }
    try {
      afterReplaceValidation?.();
      const publishedManifest = discoverRouteManifest(projectRoot, config.routes);
      if (publishedManifest.generation.sourceSha256 !== manifest.generation.sourceSha256) fail("SOURCE_CHANGED_AFTER_REPLACE");
    } catch (error) {
      rmSync(output, { recursive: true, force: true });
      if (hadOutput && existsSync(previous)) renameSync(previous, output);
      throw error;
    }
    if (operationFailure !== "cleanup") rmSync(previous, { recursive: true, force: true });
    return { changed: true, output, sourceSha256: manifest.generation.sourceSha256 };
  } finally {
    rmSync(pending, { recursive: true, force: true });
  }
}
